/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controller.KayitDialogYonetici;
import model.Kullanici;

/**
 *
 * @author asimsinanyuksel
 */
public class KayitFrame extends javax.swing.JFrame {
    private Kullanici kullanici=new Kullanici();
    KayitDialogYonetici dialogYonetici;
           
    /**
     * Creates new form NewJFrame
     */
    public KayitFrame() {
        initComponents();
        dialogYonetici =new KayitDialogYonetici(kullanici,kayitDialog);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kayitDialog = new javax.swing.JDialog();
        kaydetButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        adSoyadTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        kadTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sifreTextField = new javax.swing.JPasswordField();
        kayitOlButton = new javax.swing.JButton();
        kayitPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adLabel = new javax.swing.JLabel();
        kadLabel = new javax.swing.JLabel();
        sifreLabel = new javax.swing.JLabel();

        kayitDialog.setTitle("Kayıt Bilgileri");
        kayitDialog.setMinimumSize(new java.awt.Dimension(369, 187));

        kaydetButton.setText("Kaydet");
        kaydetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Ad Soyad:");

        jLabel1.setText("Kullanıcı Adı:");

        jLabel6.setText("Şifre:");

        javax.swing.GroupLayout kayitDialogLayout = new javax.swing.GroupLayout(kayitDialog.getContentPane());
        kayitDialog.getContentPane().setLayout(kayitDialogLayout);
        kayitDialogLayout.setHorizontalGroup(
            kayitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kayitDialogLayout.createSequentialGroup()
                .addGroup(kayitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kayitDialogLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(kaydetButton))
                    .addGroup(kayitDialogLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(kayitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kayitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sifreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adSoyadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(79, 79, 79))
        );

        kayitDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {adSoyadTextField, kadTextField, sifreTextField});

        kayitDialogLayout.setVerticalGroup(
            kayitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kayitDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kayitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(adSoyadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kayitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kayitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sifreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(kaydetButton)
                .addGap(23, 23, 23))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kayitOlButton.setText("Kayıt Ol");
        kayitOlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitOlButtonActionPerformed(evt);
            }
        });

        kayitPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kayıt Bilgileri", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel2.setText("Ad Soyad:");

        jLabel3.setText("Kullanıcı Adı:");

        jLabel4.setText("Şifre:");

        javax.swing.GroupLayout kayitPanelLayout = new javax.swing.GroupLayout(kayitPanel);
        kayitPanel.setLayout(kayitPanelLayout);
        kayitPanelLayout.setHorizontalGroup(
            kayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kayitPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(kayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kayitPanelLayout.createSequentialGroup()
                        .addComponent(sifreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42)))
                .addGap(64, 64, 64))
        );
        kayitPanelLayout.setVerticalGroup(
            kayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kayitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sifreLabel))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        kayitPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {adLabel, kadLabel, sifreLabel});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kayitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(kayitOlButton)))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kayitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(kayitOlButton)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kaydetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetButtonActionPerformed
            dialogYonetici.kullaniciBilgileriniAyarla(adSoyadTextField.getText(), kadTextField.getText(), sifreTextField.getText());
        
            adLabel.setText(kullanici.getAdSoyad());
            kadLabel.setText(kullanici.getKullaniciAdi());
            sifreLabel.setText(kullanici.getSifre());
            dialogYonetici.dialogKapat();
    }//GEN-LAST:event_kaydetButtonActionPerformed

    private void kayitOlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitOlButtonActionPerformed

          dialogYonetici.dialogGoster();
    }//GEN-LAST:event_kayitOlButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KayitFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adLabel;
    private javax.swing.JTextField adSoyadTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel kadLabel;
    private javax.swing.JTextField kadTextField;
    private javax.swing.JButton kaydetButton;
    private javax.swing.JDialog kayitDialog;
    private javax.swing.JButton kayitOlButton;
    private javax.swing.JPanel kayitPanel;
    private javax.swing.JLabel sifreLabel;
    private javax.swing.JPasswordField sifreTextField;
    // End of variables declaration//GEN-END:variables
}
